### ISSUE TITLE
Need help about flutter bluetooth!

### ISSUE THREAD

**Issue by km1220** [km1220/flutter-bluetooth#1]
Hi everyone!
I was developing with flutter and the project is about taxi service providing
and need google map, api integrations and Bluetooth also.

But I don't know how can I use bluetooth device directly.
Please send me your advice or contact address to help me, please.
Thanks a lot.

**Comment by ninja1002** [comment]
Hi
Please contact me via email 
I can help you.

**Comment by ninja1002** [comment]
john1220@gmail.com

**Comment by km1220** [comment]
> [john1220@gmail.com](mailto:john1220@gmail.com)

Thank you for your help!!!
Now I can do this.
